document.getElementById('radarForm').addEventListener('submit', function (e) {
    e.preventDefault();

    const terminal = document.getElementById('terminalOutput');
    const overlay = document.getElementById('resultOverlay');
    const zip = document.getElementById('zipCode').value;
    const agency = document.getElementById('agency').value;

    // Reset
    terminal.innerHTML = '<div class="log-line">System Ready...</div>';
    overlay.style.display = 'none';

    const logs = [
        `Initiating secure handshake...`,
        `Target Zone: ${zip} [Confirmed]`,
        `Analyzing Agency: ${agency.toUpperCase()}...`,
        `Connecting to DOJ Grant Database (doj.gov)...`,
        `<span class="log-warn">WARNING: High Traffic Anomaly detected in Sector ${zip}.</span>`,
        `Querying Governor's Public Safety Office (OLS)...`,
        `Downloading FY2025 Ledger...`,
        `Parsing 14,200 records...`,
        `Cross-referencing Charge Code against Grant Metrics...`,
        `<span class="log-danger">MATCH FOUND: Grant ID #4862402</span>`,
        `Retrieving Grant Scope: "High Visibility Interdiction"...`,
        `Correlating Arrest Timestamp with Shift Differential...`,
        `Calculating Quota Probability...`,
        `Scan Complete.`
    ];

    let delay = 0;

    logs.forEach((log, index) => {
        setTimeout(() => {
            const div = document.createElement('div');
            div.className = 'log-line';
            div.innerHTML = `> ${log}`;
            terminal.appendChild(div);
            terminal.scrollTop = terminal.scrollHeight;
        }, delay);
        delay += Math.random() * 800 + 400; // Random delay between 400-1200ms
    });

    // Show result after all logs
    setTimeout(() => {
        overlay.style.display = 'flex';
    }, delay + 500);
});

// EXPORT REPORT FUNCTIONALITY
document.getElementById('exportBtn').addEventListener('click', function () {
    const zip = document.getElementById('zipCode').value;
    const agency = document.getElementById('agency').value;
    const charge = document.getElementById('charge').value;
    const date = new Date().toISOString().split('T')[0];

    const content = `CIVIL SHIELD - FORENSIC GRANT ANALYIS REPORT
--------------------------------------------------
DATE: ${date}
REF ID: CS-${Math.floor(Math.random() * 90000) + 10000}

SUBJECT PARAMETERS:
- Zip Code: ${zip}
- Agency: ${agency.toUpperCase()}
- Charge Category: ${charge.toUpperCase()}

SCAN RESULTS:
[PASSED] DOJ Grant Database Connection
[PASSED] Governor's Public Safety Office Query
[ALERT]  High Traffic Anomaly in Sector ${zip}

!!! MATCH DETECTED !!!
GRANT ID: #4862402 (Operation Lone Star)
AMOUNT: $741,255.24
SCOPE: "High Visibility Interdiction"
QUOTA PROBABILITY: 94.2%

ANALYSIS:
The arrest in question strongly correlates with "Metric Harvesting" periods required to validate state grant funding. The officer's behavior aligns with "Yield-Based Policing" incentivized by the grant requirements.

RECOMMENDATION:
File a Discovery Request for "Grant-to-Arrest" directives under the Texas Public Information Act.
--------------------------------------------------
GENERATED BY CIVIL SHIELD (civilshield.org)
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Civil_Shield_Grant_Report_${date}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
});
